package gateway

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	accountapp "github.com/chenyme/grok2api/backend/internal/application/account"
	clientkeyapp "github.com/chenyme/grok2api/backend/internal/application/clientkey"
	accountdomain "github.com/chenyme/grok2api/backend/internal/domain/account"
	"github.com/chenyme/grok2api/backend/internal/domain/audit"
	"github.com/chenyme/grok2api/backend/internal/domain/clientkey"
	inferencedomain "github.com/chenyme/grok2api/backend/internal/domain/inference"
	mediadomain "github.com/chenyme/grok2api/backend/internal/domain/media"
	modeldomain "github.com/chenyme/grok2api/backend/internal/domain/model"
	infraegress "github.com/chenyme/grok2api/backend/internal/infra/egress"
	"github.com/chenyme/grok2api/backend/internal/infra/provider"
	"github.com/chenyme/grok2api/backend/internal/infra/security"
	neterrorpkg "github.com/chenyme/grok2api/backend/internal/pkg/neterror"
	"github.com/chenyme/grok2api/backend/internal/repository"
)

var (
	ErrModelNotFound              = errors.New("模型不存在或未启用")
	ErrNoAvailableAccount         = errors.New("没有可用上游账号")
	ErrResponseNotFound           = errors.New("Response 不存在或已过期")
	ErrResponseAccountUnavailable = errors.New("Response 绑定的上游账号不可用")
	ErrResponseStateUnsupported   = errors.New("目标模型不支持有状态 Response")
	ErrConversationUnsupported    = errors.New("目标模型不支持当前对话协议")
	ErrVideoInputTooLarge         = errors.New("视频参考图片总大小超过 32 MiB")
	ErrLedgerUnavailable          = errors.New("计费账本暂不可用")
)

const responseOwnershipTTL = 30 * 24 * time.Hour
const finalizationTimeout = 5 * time.Second
const minimumTextBillingReservationTTL = 2 * time.Hour
const billingReservationCrashGrace = 10 * time.Minute
const mediaBillingReservationTTL = 24 * time.Hour
const modelCatalogRefreshTimeout = 30 * time.Second
const accountStateWriteTimeout = 3 * time.Second

var freeQuotaUsagePattern = regexp.MustCompile(`(?i)tokens\s*\(actual/limit\)\s*:\s*([0-9]+)\s*/\s*([0-9]+)`)

type Input struct {
	RequestID       string
	ClientKey       clientkey.Key
	PublicModel     string
	Body            []byte
	Streaming       bool
	PromptCacheKey  string
	PromptCacheSeed string
	// AllowClientToolCacheRoute indicates that the client request is compatible with the Build mixed-tool cache route.
	// It only controls whether native x_search is added to existing client tools; it is not an authentication result.
	AllowClientToolCacheRoute bool
	PreviousResponseID        string
	// GrokTurnIndex forwards only the turn supplied by a real Grok Shell client; the server never infers or increments it.
	GrokTurnIndex string
	Operation     audit.Operation
}

type Usage struct {
	InputTokens            int64
	CachedInputTokens      int64
	OutputTokens           int64
	ReasoningTokens        int64
	TotalTokens            int64
	CostInUSDTicks         int64
	NumSourcesUsed         int64
	NumServerSideToolsUsed int64
	ContextInputTokens     int64
	ContextOutputTokens    int64
	ResponseModel          string
}

type Result struct {
	StatusCode          int
	Status              string
	Header              http.Header
	Body                io.ReadCloser
	RecordStreamFailure func(StreamFailureDiagnostic)
	Finalize            func(usage Usage, responseID, errorCode string)
}

// StreamFailureDiagnostic safely projects a failure termination event returned in-stream after downstream 2xx headers.
// Body contains only transport-extracted error fields and still receives the standard redaction and size limits.
type StreamFailureDiagnostic struct {
	Body          []byte
	BodyTruncated bool
}

type auditRecorder interface {
	Create(ctx context.Context, value audit.Record) error
}

type ledgerReadinessChecker interface {
	CheckLedgerReady() error
}

type routeResolver interface {
	Get(ctx context.Context, id uint64) (modeldomain.Route, error)
	GetByPublicID(ctx context.Context, publicID string) (modeldomain.Route, error)
	GetByPublicIDCandidates(ctx context.Context, publicID string) ([]modeldomain.Route, error)
	GetByProviderUpstream(ctx context.Context, providerValue accountdomain.Provider, upstreamModel string) (modeldomain.Route, error)
}

// videoAssetStore archives and reads video results generated by a Provider.
type videoAssetStore interface {
	SaveVideo(ctx context.Context, jobID, contentType string, body io.Reader) (mediadomain.Asset, error)
	OpenVideo(ctx context.Context, id string) (mediadomain.Asset, io.ReadCloser, error)
}

type accountModelSyncer interface {
	SyncAccount(ctx context.Context, accountID uint64) (int, error)
}

// resinLeaseRotator releases sticky proxy bindings (Resin admin).
type resinLeaseRotator interface {
	Enabled() bool
	RotateAccountLease(ctx context.Context, account string) (oldEgressIP, oldNodeHash string, err error)
}

// proxyClientDropper closes cached Build proxy HTTP clients so a new CONNECT is opened.
type proxyClientDropper interface {
	DropBuildProxyClients()
}

// Service handles model routing, account selection, failover, and audit finalization.
type Service struct {
	models               routeResolver
	audits               auditRecorder
	accounts             *accountapp.Service
	clientKeys           *clientkeyapp.Service
	providers            *provider.Registry
	selector             *Selector
	responses            repository.ResponseRepository
	resinAdmin           resinLeaseRotator
	proxyClients         proxyClientDropper
	// spendingLimitMaxEgressRotations: extra same-account Resin releases per request (default 3).
	spendingLimitMaxEgressRotations atomic.Int64
	// spendingLimitSoftCooldown: soft park duration after egress retries exhausted (default 1h).
	spendingLimitSoftCooldown       atomic.Int64
	maxAttempts          atomic.Int64
	retryPolicy          atomic.Pointer[retryPolicySnapshot]
	buildForbiddenReauth atomic.Pointer[buildForbiddenReauthPolicy]
	requestTimeout       atomic.Int64
	mediaJobs            repository.MediaJobRepository
	mediaAssets          videoAssetStore
	mediaQueue           chan string
	mediaMu              sync.Mutex
	mediaQueued          map[string]struct{}
	mediaWorker          int
	mediaQueueFull       atomic.Uint64
	logger               *slog.Logger
	rateLimitMu          sync.Mutex
	rateLimits           map[string]teamModelRateLimit
	rateLimitTeams       map[uint64]string
	modelSyncMu          sync.Mutex
	modelSyncing         map[uint64]struct{}
}

type teamModelRateLimit struct {
	TeamFingerprint string
	Until           time.Time
}

type buildForbiddenReauthPolicy struct {
	enabled bool
	codes   map[string]struct{}
}

// retryPolicySnapshot is an immutable retry policy published atomically.
type retryPolicySnapshot struct {
	statusCodes        map[int]struct{} // empty => legacy defaults (402/403/429/5xx)
	maxSameFingerprint int
	retry5xxWildcard   bool
}

func defaultRetryPolicySnapshot() *retryPolicySnapshot {
	return &retryPolicySnapshot{
		statusCodes:        nil,
		maxSameFingerprint: 2,
		retry5xxWildcard:   true,
	}
}

func (s *Service) ConfigureMedia(repository repository.MediaJobRepository, concurrency int) {
	if concurrency <= 0 {
		concurrency = 4
	}
	s.mediaJobs = repository
	s.mediaWorker = concurrency
	s.mediaQueue = make(chan string, min(2048, max(64, concurrency*32)))
	s.mediaQueued = make(map[string]struct{})
}

// ConfigureMediaAssets injects optional local video asset archival and reading.
func (s *Service) ConfigureMediaAssets(store videoAssetStore) {
	s.mediaAssets = store
}

func NewService(models routeResolver, audits auditRecorder, accounts *accountapp.Service, clientKeys *clientkeyapp.Service, providers *provider.Registry, selector *Selector, responses repository.ResponseRepository, maxAttempts int) *Service {
	service := &Service{
		models: models, audits: audits, accounts: accounts, clientKeys: clientKeys, providers: providers,
		selector: selector, responses: responses, logger: slog.Default(),
		rateLimits: make(map[string]teamModelRateLimit), rateLimitTeams: make(map[uint64]string),
		modelSyncing: make(map[uint64]struct{}),
	}
	service.UpdateMaxAttempts(maxAttempts)
	service.UpdateRetryPolicy(nil, 2)
	return service
}

// ConfigureResinEgress enables sticky-lease release on spending-limit 402.
func (s *Service) ConfigureResinEgress(admin resinLeaseRotator, proxyClients proxyClientDropper) {
	if s == nil {
		return
	}
	s.resinAdmin = admin
	s.proxyClients = proxyClients
}

// ConfigureSpendingLimitPolicy sets same-account egress rotate count and soft cooldown.
// maxEgressRotations is extra Resin releases after the first 402 (0→default 3, cap 10).
// softCooldown zero → 1h.
func (s *Service) ConfigureSpendingLimitPolicy(maxEgressRotations int, softCooldown time.Duration) {
	if s == nil {
		return
	}
	if maxEgressRotations <= 0 {
		maxEgressRotations = 3
	}
	if maxEgressRotations > 10 {
		maxEgressRotations = 10
	}
	if softCooldown <= 0 {
		softCooldown = time.Hour
	}
	if softCooldown > 72*time.Hour {
		softCooldown = 72 * time.Hour
	}
	s.spendingLimitMaxEgressRotations.Store(int64(maxEgressRotations))
	s.spendingLimitSoftCooldown.Store(int64(softCooldown))
}

func (s *Service) spendingLimitPolicy() (maxRotations int, softCooldown time.Duration) {
	maxRotations = int(s.spendingLimitMaxEgressRotations.Load())
	if maxRotations <= 0 {
		maxRotations = 3
	}
	softCooldown = time.Duration(s.spendingLimitSoftCooldown.Load())
	if softCooldown <= 0 {
		softCooldown = time.Hour
	}
	return maxRotations, softCooldown
}

// UpdateRetryPolicy replaces which upstream HTTP statuses trigger account rotation
// and how many identical non-account failures stop the loop.
// statusCodes nil/empty keeps legacy defaults (402, 403, 429, and all 5xx).
func (s *Service) UpdateRetryPolicy(statusCodes []int, maxSameFingerprint int) {
	if maxSameFingerprint < 1 {
		maxSameFingerprint = 2
	}
	if maxSameFingerprint > 10 {
		maxSameFingerprint = 10
	}
	policy := &retryPolicySnapshot{maxSameFingerprint: maxSameFingerprint, retry5xxWildcard: true}
	if len(statusCodes) > 0 {
		policy.statusCodes = make(map[int]struct{}, len(statusCodes))
		policy.retry5xxWildcard = false
		for _, code := range statusCodes {
			if code < 400 || code > 599 {
				continue
			}
			policy.statusCodes[code] = struct{}{}
			if code >= 500 {
				policy.retry5xxWildcard = true
			}
		}
		if len(policy.statusCodes) == 0 {
			policy.statusCodes = nil
			policy.retry5xxWildcard = true
		}
	}
	s.retryPolicy.Store(policy)
}

func (s *Service) currentRetryPolicy() *retryPolicySnapshot {
	if policy := s.retryPolicy.Load(); policy != nil {
		return policy
	}
	return defaultRetryPolicySnapshot()
}

func (s *Service) statusAllowsRetry(status int) bool {
	policy := s.currentRetryPolicy()
	if policy.statusCodes == nil {
		return isRetryable(status)
	}
	if _, ok := policy.statusCodes[status]; ok {
		return true
	}
	if policy.retry5xxWildcard && status >= 500 {
		return true
	}
	return false
}

// UpdateBuildForbiddenReauthPolicy atomically replaces the Build account invalidation policy.
func (s *Service) UpdateBuildForbiddenReauthPolicy(enabled bool, codes []string) {
	policy := &buildForbiddenReauthPolicy{enabled: enabled, codes: make(map[string]struct{}, len(codes))}
	for _, value := range codes {
		code := strings.ToLower(strings.TrimSpace(value))
		if code != "" {
			policy.codes[code] = struct{}{}
		}
	}
	s.buildForbiddenReauth.Store(policy)
}

func (s *Service) shouldInvalidateBuildForbidden(failure *UpstreamFailure) bool {
	if failure == nil || failure.HTTPStatus != http.StatusForbidden {
		return false
	}
	// Request-level safety / content policy must never trigger account invalidation.
	if failure.RequestScoped {
		return false
	}
	policy := s.buildForbiddenReauth.Load()
	if policy == nil || !policy.enabled {
		return false
	}
	_, matched := policy.codes[strings.ToLower(strings.TrimSpace(failure.UpstreamCode))]
	return matched
}

func (s *Service) markReauthRequired(ctx context.Context, requestID string, credential accountdomain.Credential, reason string) bool {
	writeCtx, cancel := context.WithTimeout(context.WithoutCancel(ctx), accountStateWriteTimeout)
	defer cancel()
	if err := s.accounts.MarkReauthRequired(writeCtx, credential.ID, reason); err != nil {
		s.logger.Error("account_reauth_required_write_failed", "request_id", requestID, "account_id", credential.ID, "provider", credential.Provider, "error", err)
		return false
	}
	s.selector.MarkQuotaStateChanged(credential.Provider)
	return true
}

func teamModelRateLimitKey(providerValue accountdomain.Provider, teamFingerprint, upstreamModel string) string {
	return string(providerValue) + "\x00" + teamFingerprint + "\x00" + strings.TrimSpace(upstreamModel)
}

func rateLimitTeamFingerprint(teamID string) string {
	teamID = strings.TrimSpace(teamID)
	if teamID == "" {
		return ""
	}
	return security.HashToken(teamID)
}

func shortTeamFingerprint(value string) string {
	if len(value) <= 12 {
		return value
	}
	return value[:12]
}

func (s *Service) activeTeamModelRateLimit(credential accountdomain.Credential, upstreamModel string, now time.Time) (teamModelRateLimit, bool) {
	teamFingerprint := rateLimitTeamFingerprint(credential.TeamID)
	s.rateLimitMu.Lock()
	defer s.rateLimitMu.Unlock()
	if teamFingerprint == "" {
		teamFingerprint = s.rateLimitTeams[credential.ID]
	}
	if teamFingerprint == "" {
		return teamModelRateLimit{}, false
	}
	key := teamModelRateLimitKey(credential.Provider, teamFingerprint, upstreamModel)
	value, ok := s.rateLimits[key]
	if !ok {
		return teamModelRateLimit{}, false
	}
	if !now.Before(value.Until) {
		delete(s.rateLimits, key)
		return teamModelRateLimit{}, false
	}
	return value, true
}

func (s *Service) markTeamModelRateLimit(credential accountdomain.Credential, upstreamModel string, metadata provider.RateLimitMetadata, now time.Time) teamModelRateLimit {
	retryAfter := metadata.RetryAfter
	if retryAfter <= 0 {
		retryAfter = time.Minute
	}
	teamFingerprint := rateLimitTeamFingerprint(metadata.TeamID)
	value := teamModelRateLimit{TeamFingerprint: shortTeamFingerprint(teamFingerprint), Until: now.Add(retryAfter)}
	key := teamModelRateLimitKey(credential.Provider, teamFingerprint, upstreamModel)
	until := now.Add(retryAfter)
	s.rateLimitMu.Lock()
	if s.rateLimits == nil {
		s.rateLimits = make(map[string]teamModelRateLimit)
	}
	if s.rateLimitTeams == nil {
		s.rateLimitTeams = make(map[uint64]string)
	}
	s.rateLimitTeams[credential.ID] = teamFingerprint
	for existingKey, value := range s.rateLimits {
		if !now.Before(value.Until) {
			delete(s.rateLimits, existingKey)
		}
	}
	if current, ok := s.rateLimits[key]; ok && !current.Until.Before(until) {
		value = current
	} else {
		s.rateLimits[key] = value
	}
	s.rateLimitMu.Unlock()
	return value
}

// PrewarmSelector loads routing candidates for common routes so the first real
// request after process start does not pay a multi-second SQLite candidate scan.
func (s *Service) PrewarmSelector(ctx context.Context, routes []struct {
	Provider      accountdomain.Provider
	UpstreamModel string
	QuotaMode     string
}) {
	if s == nil || s.selector == nil {
		return
	}
	for _, route := range routes {
		if err := s.selector.Prewarm(ctx, route.Provider, route.UpstreamModel, route.QuotaMode); err != nil {
			if s.logger != nil {
				s.logger.Warn("selector_prewarm_failed", "provider", route.Provider, "upstream_model", route.UpstreamModel, "error", err)
			}
			continue
		}
		if s.logger != nil {
			s.logger.Info("selector_prewarm_ok", "provider", route.Provider, "upstream_model", route.UpstreamModel)
		}
	}
}

func (s *Service) SetLogger(logger *slog.Logger) {
	if logger != nil {
		s.logger = logger
	}
}

func (s *Service) UpdateMaxAttempts(maxAttempts int) { s.maxAttempts.Store(int64(maxAttempts)) }

func (s *Service) UpdateRequestTimeout(value time.Duration) {
	if value <= 0 {
		value = minimumTextBillingReservationTTL
	}
	s.requestTimeout.Store(int64(value))
}

func (s *Service) textBillingReservationTTL() time.Duration {
	ttl := time.Duration(s.requestTimeout.Load()) + finalizationTimeout + billingReservationCrashGrace
	return max(minimumTextBillingReservationTTL, ttl)
}

func (s *Service) checkLedgerReady() error {
	checker, ok := s.audits.(ledgerReadinessChecker)
	if !ok {
		return nil
	}
	if err := checker.CheckLedgerReady(); err != nil {
		return ErrLedgerUnavailable
	}
	return nil
}

func (s *Service) CreateResponse(ctx context.Context, input Input) (*Result, error) {
	input.Operation = audit.OperationResponses
	if isResponsesCompactionRequest(input.Body) {
		input.Operation = audit.OperationCompaction
	}
	return s.createResponseAt(ctx, input, "/responses")
}

func (s *Service) CreateChatCompletion(ctx context.Context, input Input) (*Result, error) {
	input.Operation = audit.OperationChat
	return s.createResponseAt(ctx, input, "/responses")
}

// CreateMessage executes an Anthropic Messages request through the unified Responses upstream.
func (s *Service) CreateMessage(ctx context.Context, input Input) (*Result, error) {
	input.Operation = audit.OperationMessages
	return s.createResponseAt(ctx, input, "/responses")
}

func (s *Service) CompactResponse(ctx context.Context, input Input) (*Result, error) {
	input.Streaming = false
	input.Operation = audit.OperationCompaction
	return s.createResponseAt(ctx, input, "/responses/compact")
}

// resolvePublicModelRoutes supports both unprefixed downstream model names and explicitly sourced compatibility names.
func (s *Service) resolvePublicModelRoutes(ctx context.Context, publicModel string) ([]modeldomain.Route, string, error) {
	routes, err := s.models.GetByPublicIDCandidates(ctx, publicModel)
	if err == nil {
		return routes, "", nil
	}
	if s.providers == nil {
		return nil, "", err
	}
	alias, ok := s.providers.ResolveModelAlias(publicModel)
	if !ok {
		return nil, "", err
	}
	if alias.Provider != "" && alias.UpstreamModel != "" {
		route, routeErr := s.models.GetByProviderUpstream(ctx, alias.Provider, alias.UpstreamModel)
		if routeErr != nil {
			return nil, "", routeErr
		}
		return []modeldomain.Route{route}, alias.ReasoningEffort, nil
	}
	routes, err = s.models.GetByPublicIDCandidates(ctx, alias.PublicModel)
	return routes, alias.ReasoningEffort, err
}

// selectConversationRoute selects a route for the named model that satisfies permissions, protocol, and session affinity.
func (s *Service) selectConversationRoute(routes []modeldomain.Route, key clientkey.Key, operation audit.Operation, path string, requireStoredResponse bool, ownership *inferencedomain.ResponseOwnership) (modeldomain.Route, error) {
	if len(routes) == 0 || s.providers == nil {
		return modeldomain.Route{}, ErrModelNotFound
	}
	fallback := routes[0]
	matchedOwnership := ownership == nil
	allowed := false
	conversationSupported := false
	storedResponseUnsupported := false
	for _, route := range routes {
		if ownership != nil && route.Provider != ownership.Provider {
			continue
		}
		matchedOwnership = true
		fallback = route
		if !s.clientKeys.CanUseModel(key, route.ID) {
			continue
		}
		allowed = true
		if !s.providers.SupportsConversation(route.Provider, string(operation)) {
			continue
		}
		conversationSupported = true
		if path == "/responses/compact" && !s.providers.SupportsResponseCompaction(route.Provider) {
			continue
		}
		if requireStoredResponse && !s.providers.SupportsStoredResponses(route.Provider) {
			storedResponseUnsupported = true
			continue
		}
		return route, nil
	}
	if !matchedOwnership {
		return fallback, ErrResponseAccountUnavailable
	}
	if !allowed {
		return fallback, clientkeyapp.ErrModelNotAllowed
	}
	if storedResponseUnsupported {
		return fallback, ErrResponseStateUnsupported
	}
	if conversationSupported && path == "/responses/compact" {
		return fallback, ErrConversationUnsupported
	}
	return fallback, ErrConversationUnsupported
}

// selectMediaRoute selects a same-name route that satisfies media capability, key permissions, and Provider support.
func (s *Service) selectMediaRoute(routes []modeldomain.Route, key clientkey.Key, capability modeldomain.Capability, providerSupported func(accountdomain.Provider) bool) (modeldomain.Route, error) {
	if len(routes) == 0 {
		return modeldomain.Route{}, ErrModelNotFound
	}
	fallback := routes[0]
	capabilityMatched := false
	allowed := false
	for _, route := range routes {
		if route.Capability != capability {
			continue
		}
		fallback = route
		capabilityMatched = true
		if !s.clientKeys.CanUseModel(key, route.ID) {
			continue
		}
		allowed = true
		if providerSupported(route.Provider) {
			return route, nil
		}
	}
	if !capabilityMatched {
		return fallback, ErrModelNotFound
	}
	if !allowed {
		return fallback, clientkeyapp.ErrModelNotAllowed
	}
	return fallback, ErrNoAvailableAccount
}

func (s *Service) createResponseAt(ctx context.Context, input Input, path string) (*Result, error) {
	ctx, egressTrace := infraegress.WithTrace(ctx)
	startedAt := time.Now()
	eventID := newAuditEventID()
	operation := input.Operation
	if operation == "" {
		operation = audit.OperationResponses
	}
	routes, aliasEffort, err := s.resolvePublicModelRoutes(ctx, input.PublicModel)
	if err != nil {
		return nil, ErrModelNotFound
	}
	// Select the route first instead of requiring stored Responses support up front. Console is stateless
	// but still accepts complete history; Provider-level normalization handles the compatibility details.
	route, routeErr := s.selectConversationRoute(routes, input.ClientKey, operation, path, false, nil)
	var ownership *inferencedomain.ResponseOwnership
	if input.PreviousResponseID != "" && routeErr == nil {
		if s.providers.SupportsStoredResponses(route.Provider) {
			value, ownershipErr := s.responses.Get(ctx, input.PreviousResponseID, input.ClientKey.ID, time.Now().UTC())
			if ownershipErr != nil {
				return nil, ErrResponseNotFound
			}
			ownership = &value
			route, routeErr = s.selectConversationRoute(routes, input.ClientKey, operation, path, true, ownership)
		} else if route.Provider == accountdomain.ProviderConsole {
			// Console does not retain Response state, so replay the history statelessly here;
			// Provider normalization removes stale Response IDs.
			input.PreviousResponseID = ""
		} else {
			return nil, ErrResponseStateUnsupported
		}
	}
	publicModel := modeldomain.ExternalPublicID(route.Provider, route.PublicID)
	input.PublicModel = publicModel
	if aliasEffort != "" {
		input.Body, err = rewriteAliasedModel(input.Body, publicModel, aliasEffort, operation)
		if err != nil {
			return nil, err
		}
	}
	if routeErr != nil && !errors.Is(routeErr, clientkeyapp.ErrModelNotAllowed) {
		return nil, routeErr
	}
	timing := newGenerationTiming(publicModel, route.Provider)
	timingHandedOff := false
	defer func() {
		if !timingHandedOff {
			timing.finish(s.logger, "failed")
		}
	}()
	usageSource := audit.UsageSourceUpstream
	if usageKind, _ := s.providers.UsageKind(route.Provider); usageKind == provider.UsageEstimated {
		usageSource = audit.UsageSourceEstimated
	}
	mediaSummary, _ := summarizeResponseMedia(input.Body)
	logResponseMediaSummary(s.logger, input.RequestID, mediaSummary)
	auditBase := audit.Record{
		EventID: eventID, RequestID: input.RequestID, ClientKeyID: input.ClientKey.ID, ClientKeyName: input.ClientKey.Name,
		ModelRouteID: route.ID, ModelPublicID: publicModel, ModelUpstreamModel: modeldomain.DisplayUpstreamModel(route.Provider, route.UpstreamModel),
		Provider: string(route.Provider), Operation: operation, UsageSource: usageSource, Streaming: input.Streaming,
		MediaInputImages: mediaSummary.InputImages,
	}
	if errors.Is(routeErr, clientkeyapp.ErrModelNotAllowed) {
		record := auditBase
		record.StatusCode = http.StatusForbidden
		record.DurationMS = time.Since(startedAt).Milliseconds()
		record.ErrorCode = "model_not_allowed"
		record.CreatedAt = time.Now().UTC()
		applyAuditEgress(&record, egressTrace, route.Provider)
		if err := s.audits.Create(ctx, record); err != nil {
			s.logger.Error("request_usage_write_failed", "event_id", record.EventID, "request_id", input.RequestID, "error", err)
		}
		return nil, clientkeyapp.ErrModelNotAllowed
	}
	affinityKey := ""
	ownershipPromptCacheKey := ""
	reasoningReplayKey := ""
	if route.Provider == accountdomain.ProviderBuild {
		// Derive a stable identity from explicit session signals, message anchors, and model; never generate a random conv-id.
		identity := buildSessionIdentity{}
		if ownership != nil && ownership.PromptCacheKey != "" {
			// previous_response_id belongs to an existing Response chain and must inherit the root session identity;
			// do not recompute the soft key from this turn's incremental input.
			identity.upstreamID = ownership.PromptCacheKey
			identity.replayKey = ownership.ReasoningReplayKey
		} else {
			identity = resolveBuildSessionIdentity(
				input.ClientKey.ID,
				route.Provider,
				route.UpstreamModel,
				input.PromptCacheKey,
				input.PromptCacheSeed,
				input.Body,
			)
		}
		seedLen := len(strings.TrimSpace(input.PromptCacheSeed))
		explicitKeyLen := len(strings.TrimSpace(input.PromptCacheKey))
		seedPresent := seedLen > 0 || explicitKeyLen > 0
		input.PromptCacheKey = identity.upstreamID
		affinityKey = identity.affinityKey
		ownershipPromptCacheKey = identity.upstreamID
		reasoningReplayKey = identity.replayKey
		// Info-level so ops can see why multi-turn cache is cold (empty/soft/no sticky seed).
		switch {
		case identity.upstreamID == "":
			s.logger.Info("prompt_cache_session_empty", "request_id", input.RequestID, "model", route.UpstreamModel, "provider", route.Provider,
				"hint", "no session seed; sticky+cache disabled — send X-Claude-Code-Session-Id / prompt_cache_key")
		case identity.soft:
			// Soft = no client session header. Affinity is first-user (+ optional assistant dual-key).
			bodyProbe := input.Body
			if len(bodyProbe) > 65536 {
				bodyProbe = bodyProbe[:65536]
			}
			bodyText := string(bodyProbe)
			s.logger.Info("prompt_cache_session_soft", "request_id", input.RequestID, "model", route.UpstreamModel,
				"cache_key_prefix", truncateForLog(identity.upstreamID, 12), "has_affinity", affinityKey != "",
				"dual_affinity", strings.Contains(affinityKey, affinityKeySeparator),
				"body_has_prompt_cache_key", strings.Contains(bodyText, `"prompt_cache_key"`),
				"body_has_metadata", strings.Contains(bodyText, `"metadata"`),
				"body_has_user", strings.Contains(bodyText, `"user"`),
				"seed_len", seedLen,
				"explicit_key_len", explicitKeyLen,
				"hint", "no explicit session id; prefer X-Claude-Code-Session-Id / prompt_cache_key for CPA-like cache")
		default:
			s.logger.Info("prompt_cache_session_ready", "request_id", input.RequestID, "model", route.UpstreamModel,
				"cache_key_prefix", truncateForLog(identity.upstreamID, 12), "has_affinity", affinityKey != "",
				"seed_present", seedPresent)
		}
	}
	adapter, ok := s.providers.Responses(route.Provider)
	if !ok {
		return nil, ErrNoAvailableAccount
	}
	physicalCallCtx := infraegress.WithPhysicalCallTrace(ctx, string(route.Provider), string(operation))
	supportsStoredResponses := s.providers.SupportsStoredResponses(route.Provider)
	if input.PreviousResponseID != "" && !supportsStoredResponses {
		return nil, ErrResponseStateUnsupported
	}
	// maxAttempts <= 0 means unlimited account rotation (upstream v3.0.10 routing policy).
	// Cap at a large finite bound so a runaway loop cannot hang forever.
	attempts := int(s.maxAttempts.Load())
	if attempts <= 0 {
		attempts = 1_000_000
	}
	// Same-account Resin egress rotations need extra loop slots beyond account switches.
	maxEgressRotationsBudget, _ := s.spendingLimitPolicy()
	if maxEgressRotationsBudget > 0 && attempts < 1_000_000 {
		// Worst case: every account burns 1 initial + N egress retries.
		expanded := attempts * (1 + maxEgressRotationsBudget)
		if expanded > 64 {
			expanded = 64
		}
		if expanded > attempts {
			attempts = expanded
		}
	}
	idempotencyID, _ := security.NewOpaqueToken(18)
	if ownership != nil {
		attempts = 1
	}
	pricingModel := s.providers.PricingModel(route.Provider, route.UpstreamModel)
	if err := s.checkLedgerReady(); err != nil {
		return nil, err
	}
	if reservation, priced := audit.EstimateOfficialTextReservation(pricingModel, input.Body); priced {
		if _, err := s.clientKeys.ReserveBilling(ctx, input.ClientKey, eventID, reservation.CostInUSDTicks, s.textBillingReservationTTL()); err != nil {
			return nil, err
		}
	}
	excluded := make(map[uint64]bool)
	failureFingerprints := make(map[string]int)
	authRecoveryAttempted := make(map[uint64]bool)
	// egressRotateCount tracks same-account Resin sticky releases for spending-limit 402.
	egressRotateCount := make(map[uint64]int)
	var pinRetryAccountID uint64
	pinRetryEgressForce := false
	maxEgressRotations, spendingSoftCooldown := s.spendingLimitPolicy()
	quotaMode := s.providers.QuotaMode(route.Provider, route.UpstreamModel)
	quotaProbeAttempted := false
	// permanentStickyBreak is set when we leave an account for quota/auth reasons so the
	// successful account must own the prompt_cache_key sticky for subsequent turns.
	// Temporary capacity/platform-busy rotates keep the original sticky binding.
	permanentStickyBreak := false
	var lastErr error
	var lastFailure *UpstreamFailure
	failureAttempts := newFailureAttemptRecorder(http.MethodPost, path)
	responseStartedAt := startedAt
	forwardResponse := func(lease *accountLease, credential accountdomain.Credential, billing *accountdomain.Billing) (*provider.Response, error) {
		started := time.Now()
		responseStartedAt = started
		lease.markSelectorUpstreamStarted()
		response, err := adapter.ForwardResponse(physicalCallCtx, provider.ResponseResourceRequest{Credential: credential, Billing: billing, Method: http.MethodPost, Path: path, Model: route.UpstreamModel, PromptCacheKey: input.PromptCacheKey, ReasoningReplayKey: reasoningReplayKey, AllowClientToolCacheRoute: input.AllowClientToolCacheRoute, GrokTurnIndex: input.GrokTurnIndex, IdempotencyID: idempotencyID, Body: input.Body, Streaming: input.Streaming, NormalizeBody: true, Operation: string(operation)})
		err = failureAttempts.captureResponse(credential, started, response, err)
		timing.markUpstream(time.Since(started))
		return response, err
	}
	ensureCredential := func(credential accountdomain.Credential, force bool) (accountdomain.Credential, error) {
		started := time.Now()
		result, err := s.accounts.EnsureCredential(ctx, credential, force)
		failureAttempts.captureCredentialFailure(credential, started, force, err)
		timing.markCredential(time.Since(started))
		return result, err
	}
attemptLoop:
	for attempt := 0; attempt < attempts; attempt++ {
		var lease *accountLease
		var err error
		selectionStarted := time.Now()
		if pinRetryAccountID != 0 {
			// Same-account egress retry after Resin sticky release.
			pinnedID := pinRetryAccountID
			forceEgress := pinRetryEgressForce
			pinRetryAccountID = 0
			pinRetryEgressForce = false
			if forceEgress {
				lease, err = s.selector.AcquirePinnedEgressRetry(ctx, route.Provider, pinnedID, route.UpstreamModel, quotaMode)
				if err != nil {
					// Do not end the whole request: fall back to another account.
					s.logger.Warn("egress_pin_retry_failed",
						"request_id", input.RequestID,
						"account_id", pinnedID,
						"rotation", egressRotateCount[pinnedID],
						"error", err,
					)
					excluded[pinnedID] = true
					lease, err = s.selector.Acquire(ctx, route.Provider, route.UpstreamModel, quotaMode, affinityKey, excluded, !quotaProbeAttempted)
				}
			} else {
				lease, err = s.selector.AcquirePinned(ctx, route.Provider, pinnedID, route.UpstreamModel, quotaMode, true)
			}
		} else if ownership != nil {
			lease, err = s.selector.AcquirePinned(ctx, route.Provider, ownership.AccountID, route.UpstreamModel, quotaMode, true)
		} else {
			lease, err = s.selector.Acquire(ctx, route.Provider, route.UpstreamModel, quotaMode, affinityKey, excluded, !quotaProbeAttempted)
		}
		timing.markSelection(time.Since(selectionStarted))
		if err != nil {
			if lastFailure == nil {
				lastErr = err
			}
			break
		}
		if affinityKey != "" {
			mode := lease.StickyMode
			if mode == "" {
				mode = stickyModeNone
			}
			level := slog.LevelInfo
			if mode == stickyModeBorrow || mode == stickyModeRebind {
				level = slog.LevelWarn
			}
			s.logger.Log(ctx, level, "sticky_account_selected",
				"request_id", input.RequestID,
				"account_id", lease.Credential.ID,
				"account_name", lease.Credential.Name,
				"sticky_mode", mode,
				"sticky_bound_id", lease.StickyBoundID,
				"attempt", attempt+1,
				"cache_key_prefix", truncateForLog(input.PromptCacheKey, 12),
			)
		} else if route.Provider == accountdomain.ProviderBuild {
			s.logger.Info("sticky_skipped_no_affinity",
				"request_id", input.RequestID,
				"account_id", lease.Credential.ID,
				"account_name", lease.Credential.Name,
				"attempt", attempt+1,
				"hint", "no session affinity — ready-ring may thrash accounts and kill prompt cache",
			)
		}
		excluded[lease.Credential.ID] = true
		if limited, ok := s.activeTeamModelRateLimit(lease.Credential, route.UpstreamModel, time.Now().UTC()); ok {
			lease.Release()
			lastFailure = &UpstreamFailure{
				HTTPStatus: http.StatusTooManyRequests, Code: "upstream_rate_limited", PublicMessage: "上游请求频率受限",
				Fingerprint: "429:team_model_rate_limit", RetryAfter: time.Until(limited.Until),
			}
			lastErr = fmt.Errorf("上游 Team 与模型请求频率受限")
			s.logger.Warn("upstream_team_model_rate_limit_active", "request_id", input.RequestID, "provider", route.Provider, "model", route.UpstreamModel, "team_fingerprint", limited.TeamFingerprint, "retry_after", lastFailure.RetryAfter.Round(time.Second))
			attempt--
			continue
		}
		if lease.QuotaProbe {
			quotaProbeAttempted = true
		}
		if lease.QuotaProbeKind == accountdomain.QuotaRecoveryKindPaid {
			recovered, probeErr := s.accounts.ProbePaidQuota(ctx, lease.Credential)
			s.selector.MarkQuotaStateChanged(lease.Credential.Provider)
			if probeErr != nil || !recovered {
				lease.Release()
				lastErr = firstError(probeErr, fmt.Errorf("付费额度尚未恢复"))
				continue
			}
			lease.QuotaProbe = false
			lease.QuotaProbeKind = ""
			lease.Billing = nil
		}
		credential, err := ensureCredential(lease.Credential, false)
		if err != nil {
			lease.Release()
			lastErr = err
			lastFailure = newCredentialUpstreamFailure(err, lease.Credential.ID, lease.Credential.Name)
			continue
		}
		response, err := forwardResponse(lease, credential, lease.Billing)
		if err != nil {
			lease.Release()
			lastErr = err
			if ctx.Err() != nil || errors.Is(err, context.Canceled) {
				lastFailure = &UpstreamFailure{HTTPStatus: 499, Code: "request_canceled", PublicMessage: "请求已取消", AccountID: credential.ID, AccountName: credential.Name, Cause: firstError(ctx.Err(), err)}
				break
			}
			if isSSOCredentialRejected(err, credential) {
				s.markSSOCredentialRejected(ctx, credential, fmt.Sprintf("%s SSO credential rejected", credential.Provider))
				lastFailure = newHTTPUpstreamFailure(http.StatusUnauthorized, nil, credential.ID, credential.Name)
				continue
			}
			lastFailure = newTransportUpstreamFailure(err, credential.ID, credential.Name)
			if !isRetryableTransportFailure(credential.Provider, err) {
				break
			}
			failureFingerprints[lastFailure.Fingerprint]++
			if failureFingerprints[lastFailure.Fingerprint] >= 2 {
				break
			}
			continue
		}
	handleResponse:
		if response.ModelCatalogChanged {
			s.queueAccountModelSync(credential.ID)
		}
		if response.StatusCode == http.StatusUnauthorized {
			response.Body.Close()
			if credential.AuthType == accountdomain.AuthTypeSSO {
				s.markSSOCredentialRejected(ctx, credential, fmt.Sprintf("%s SSO credential rejected", credential.Provider))
				lease.Release()
				lastErr = fmt.Errorf("%s SSO 凭据已失效", credential.Provider)
				lastFailure = newHTTPUpstreamFailure(http.StatusUnauthorized, nil, credential.ID, credential.Name)
				continue
			}
			if s.markPermanentlyUnrefreshableCredentialRejected(ctx, credential) {
				lease.Release()
				lastErr = accountapp.ErrCredentialRefreshPermanent
				lastFailure = newHTTPUpstreamFailure(http.StatusUnauthorized, nil, credential.ID, credential.Name)
				continue
			}
			authRecoveryAttempted[credential.ID] = true
			refreshed, refreshErr := ensureCredential(credential, true)
			if refreshErr == nil {
				response, err = forwardResponse(lease, refreshed, lease.Billing)
				credential = refreshed
			}
			if refreshErr != nil || err != nil {
				if errors.Is(refreshErr, accountapp.ErrCredentialRefreshPermanent) {
					s.markCredentialRejectedAfterPermanentRefresh(ctx, credential)
				}
				lease.Release()
				lastErr = firstError(refreshErr, err)
				if refreshErr != nil {
					lastFailure = newCredentialUpstreamFailure(refreshErr, credential.ID, credential.Name)
				} else if ctx.Err() != nil || errors.Is(err, context.Canceled) {
					lastFailure = &UpstreamFailure{HTTPStatus: 499, Code: "request_canceled", PublicMessage: "请求已取消", AccountID: credential.ID, AccountName: credential.Name, Cause: firstError(ctx.Err(), err)}
					break
				} else {
					lastFailure = newTransportUpstreamFailure(err, credential.ID, credential.Name)
					if !isRetryableTransportFailure(credential.Provider, err) {
						break attemptLoop
					}
				}
				continue
			}
			if response.StatusCode == http.StatusUnauthorized {
				body, _ := readRetryableBody(response.Body)
				_ = s.accounts.MarkReauthRequired(ctx, credential.ID, "Grok Build OAuth credential rejected after refresh")
				s.selector.MarkQuotaStateChanged(credential.Provider)
				lease.Release()
				lastErr = fmt.Errorf("刷新后上游仍返回 401")
				lastFailure = newHTTPUpstreamFailure(http.StatusUnauthorized, body, credential.ID, credential.Name)
				continue
			}
		}
		egressForbidden := s.providers.RetryForbiddenAsEgress(credential.Provider) && response.StatusCode == http.StatusForbidden
		finalEgressForbidden := egressForbidden && (attempt > 0 || attempt+1 >= attempts)
		// 403 must be classified by body first (upstream ba81e8d): blocked-user → reauth + rotate;
		// only non-block 403 may be treated as egress anti-bot without account penalty.
		if response.StatusCode == http.StatusForbidden {
			retryAfter := parseRetryAfter(response.Header.Get("Retry-After"), time.Now().UTC())
			body, _ := readRetryableBody(response.Body)
			lastFailure = newHTTPUpstreamFailure(response.StatusCode, body, credential.ID, credential.Name)
			if lastFailure.RequestScoped {
				lease.Release()
				lastErr = lastFailure
				s.logger.Warn("upstream_request_scoped_failure", "request_id", input.RequestID, "account_id", credential.ID, "provider", credential.Provider, "status", response.StatusCode, "upstream_code", lastFailure.UpstreamCode)
				break attemptLoop
			}
			if lastFailure.AccountBlocked {
				failureHandled := s.markReauthRequired(ctx, input.RequestID, credential, fmt.Sprintf("%s account is blocked", credential.Provider))
				if lastFailure.AccountScoped && !failureHandled {
					s.selector.MarkFailure(ctx, credential, response.StatusCode, retryAfter)
				}
				permanentStickyBreak = true
				lease.Release()
				lastErr = fmt.Errorf("上游返回 %d", response.StatusCode)
				s.logger.Warn("upstream_request_failed", "request_id", input.RequestID, "account_id", credential.ID, "provider", credential.Provider, "status", response.StatusCode, "upstream_code", lastFailure.UpstreamCode, "account_scoped", lastFailure.AccountScoped, "account_blocked", true)
				continue
			}
			if egressForbidden && !finalEgressForbidden {
				// Non-block 403: egress/session challenge — do not penalize the account.
				delete(excluded, credential.ID)
				lease.Release()
				lastErr = fmt.Errorf("上游出口会话被拒绝")
				continue
			}
			// Final non-block 403 (or non-egress provider): reattach body for shared retry path.
			response.Body = io.NopCloser(bytes.NewReader(body))
		}
		if s.isRetryableResponse(response, route.Provider) && !finalEgressForbidden {
			retryAfter := parseRetryAfter(response.Header.Get("Retry-After"), time.Now().UTC())
			body, _ := readRetryableBody(response.Body)
			lastFailure = newHTTPUpstreamFailure(response.StatusCode, body, credential.ID, credential.Name)
			// Content/safety policy: fail this request only — no OAuth refresh, no cool-down, no rotate.
			if lastFailure.RequestScoped {
				lease.Release()
				lastErr = lastFailure
				s.logger.Warn("upstream_request_scoped_failure", "request_id", input.RequestID, "account_id", credential.ID, "provider", credential.Provider, "status", response.StatusCode, "upstream_code", lastFailure.UpstreamCode)
				break attemptLoop
			}
			// Platform capacity/high-demand: rotate accounts but never cool free-usage stock.
			if lastFailure.PlatformBusy {
				lease.Release()
				lastErr = lastFailure
				s.logger.Warn("upstream_capacity_busy", "request_id", input.RequestID, "account_id", credential.ID, "provider", credential.Provider, "status", response.StatusCode, "upstream_code", lastFailure.UpstreamCode)
				failureFingerprints[lastFailure.Fingerprint]++
				if failureFingerprints[lastFailure.Fingerprint] >= s.currentRetryPolicy().maxSameFingerprint {
					break attemptLoop
				}
				continue
			}
			buildForbiddenReauth := credential.Provider == accountdomain.ProviderBuild && s.shouldInvalidateBuildForbidden(lastFailure)
			if buildForbiddenReauth {
				lastFailure.AccountScoped = true
			}
			// The adapter only allows auto Super accounts to fall back to XAI within the same request;
			// 403 from non-Super accounts triggers account-level cooldown and rotation.
			freeBuildForbidden := response.StatusCode == http.StatusForbidden && credential.Provider == accountdomain.ProviderBuild && !accountdomain.IsBuildSuper(credential, lease.Billing)
			if lastFailure.AccountBlocked || buildForbiddenReauth {
				freeBuildForbidden = false
			}
			if freeBuildForbidden {
				lastFailure.AccountScoped = true
			}
			if response.StatusCode == http.StatusTooManyRequests && response.RateLimit != nil && response.RateLimit.TeamID != "" && response.RateLimit.Model == route.UpstreamModel {
				limited := s.markTeamModelRateLimit(credential, route.UpstreamModel, *response.RateLimit, time.Now().UTC())
				lastFailure.AccountScoped = false
				lastFailure.Fingerprint = "429:team_model_rate_limit"
				lastFailure.RetryAfter = time.Until(limited.Until)
				lease.Release()
				lastErr = fmt.Errorf("上游 Team 与模型请求频率受限")
				s.logger.Warn("upstream_team_model_rate_limited", "request_id", input.RequestID, "provider", credential.Provider, "model", route.UpstreamModel, "team_fingerprint", limited.TeamFingerprint, "scope", response.RateLimit.Scope, "actual", response.RateLimit.Actual, "limit", response.RateLimit.Limit, "retry_after", lastFailure.RetryAfter)
				continue
			}
			if s.providers.SupportsCredentialRefresh(credential.Provider) && !authRecoveryAttempted[credential.ID] && credential.EncryptedRefreshToken != "" && !lastFailure.AccountBlocked && !buildForbiddenReauth && (lastFailure.PermanentAccountDenial || lastFailure.CredentialRejected) {
				authRecoveryAttempted[credential.ID] = true
				refreshed, refreshErr := ensureCredential(credential, true)
				if refreshErr != nil {
					lease.Release()
					lastErr = refreshErr
					lastFailure = newCredentialUpstreamFailure(refreshErr, credential.ID, credential.Name)
					continue attemptLoop
				}
				response, err = forwardResponse(lease, refreshed, lease.Billing)
				credential = refreshed
				if err != nil {
					lease.Release()
					lastErr = err
					if ctx.Err() != nil || errors.Is(err, context.Canceled) {
						lastFailure = &UpstreamFailure{HTTPStatus: 499, Code: "request_canceled", PublicMessage: "请求已取消", AccountID: credential.ID, AccountName: credential.Name, Cause: firstError(ctx.Err(), err)}
						break attemptLoop
					}
					lastFailure = newTransportUpstreamFailure(err, credential.ID, credential.Name)
					if !isRetryableTransportFailure(credential.Provider, err) {
						break attemptLoop
					}
					continue attemptLoop
				}
				goto handleResponse
			}
			failureHandled := false
			if freeBuildForbidden {
				s.selector.MarkFailure(ctx, credential, response.StatusCode, retryAfter)
				failureHandled = true
				permanentStickyBreak = true
			} else if lease.QuotaMode != "" && response.StatusCode == http.StatusTooManyRequests {
				exhausted, reconcileErr := s.accounts.ReconcileRateLimit(ctx, credential.ID, lease.QuotaMode, retryAfter)
				s.selector.MarkQuotaStateChanged(credential.Provider)
				failureHandled = reconcileErr == nil && exhausted
				if failureHandled {
					permanentStickyBreak = true
				}
			} else if used, limit, exhausted := parseFreeQuotaExhaustion(body); exhausted {
				s.selector.MarkFreeQuotaExhausted(ctx, credential, used, limit, quotaRecoveryHints{
					Billing: lease.Billing, QuotaMode: lease.QuotaMode, RetryAfter: retryAfter,
				})
				failureHandled = true
				permanentStickyBreak = true
			} else if lastFailure.ModelQuotaExhausted {
				s.selector.MarkModelQuotaExhausted(ctx, credential, route.UpstreamModel, retryAfter)
				failureHandled = true
				permanentStickyBreak = true
			} else if lastFailure.FreeQuotaExhausted {
				s.selector.MarkFreeQuotaExhausted(ctx, credential, 0, 0, quotaRecoveryHints{
					Billing: lease.Billing, QuotaMode: lease.QuotaMode, RetryAfter: retryAfter,
				})
				failureHandled = true
				permanentStickyBreak = true
			} else if lastFailure.QuotaExhausted {
				// spending-limit 402: rotate Resin exit up to N times on the same account,
				// then soft-cool with kind=spending_limit (not free/paid quota recovery).
				if lastFailure.EgressSuspect && credential.Provider == accountdomain.ProviderBuild {
					rotated := egressRotateCount[credential.ID]
					if rotated < maxEgressRotations &&
						s.tryRotateResinEgress(ctx, input.RequestID, credential, lease, egressRotateCount, maxEgressRotations) {
						lease.Release()
						lastErr = fmt.Errorf("上游返回 %d（出口粘性已释放 %d/%d，同号重试）", response.StatusCode, egressRotateCount[credential.ID], maxEgressRotations)
						pinRetryAccountID = credential.ID
						pinRetryEgressForce = true
						delete(excluded, credential.ID)
						continue
					}
					s.selector.MarkSpendingLimitSoftCooldown(ctx, credential, spendingSoftCooldown)
					failureHandled = true
					permanentStickyBreak = true
					s.logger.Warn("spending_limit_soft_cooldown",
						"request_id", input.RequestID,
						"account_id", credential.ID,
						"account_name", credential.Name,
						"egress_rotations", egressRotateCount[credential.ID],
						"soft_cooldown", spendingSoftCooldown.String(),
					)
				} else {
					s.selector.MarkPaymentQuotaExhausted(ctx, credential, quotaRecoveryHints{
						Billing: lease.Billing, QuotaMode: lease.QuotaMode, RetryAfter: retryAfter,
					})
					failureHandled = true
					permanentStickyBreak = true
				}
			}
			if lastFailure.AccountBlocked {
				failureHandled = s.markReauthRequired(ctx, input.RequestID, credential, fmt.Sprintf("%s account is blocked", credential.Provider))
				if failureHandled {
					permanentStickyBreak = true
				}
			} else if buildForbiddenReauth {
				failureHandled = s.markReauthRequired(ctx, input.RequestID, credential, fmt.Sprintf("%s upstream error code %s matched the invalidation policy", credential.Provider, lastFailure.UpstreamCode))
				if failureHandled {
					permanentStickyBreak = true
				}
			} else if s.providers.SupportsCredentialRefresh(credential.Provider) && lastFailure.PermanentAccountDenial {
				if credential.Provider == accountdomain.ProviderBuild {
					// A Build account may lack permission for one chat model while its OAuth credential and video
					// access remain valid. Isolate this denial to the model; reauthorization is needed only when the credential is rejected.
					s.selector.MarkModelAccessDenied(ctx, credential, route.UpstreamModel, retryAfter)
					failureHandled = true
					permanentStickyBreak = true
				} else {
					failureHandled = s.markReauthRequired(ctx, input.RequestID, credential, fmt.Sprintf("%s chat endpoint access denied", credential.Provider))
					if failureHandled {
						permanentStickyBreak = true
					}
				}
			} else if s.providers.SupportsCredentialRefresh(credential.Provider) && lastFailure.CredentialRejected {
				failureHandled = s.markReauthRequired(ctx, input.RequestID, credential, fmt.Sprintf("%s credential rejected", credential.Provider))
				if failureHandled {
					permanentStickyBreak = true
				}
			}
			if lastFailure.AccountScoped && !failureHandled {
				s.selector.MarkFailure(ctx, credential, response.StatusCode, retryAfter)
				permanentStickyBreak = true
			}
			lease.Release()
			lastErr = fmt.Errorf("上游返回 %d", response.StatusCode)
			s.logger.Warn("upstream_request_failed", "request_id", input.RequestID, "account_id", credential.ID, "provider", credential.Provider, "status", response.StatusCode, "upstream_code", lastFailure.UpstreamCode, "account_scoped", lastFailure.AccountScoped)
			if !lastFailure.AccountScoped {
				failureFingerprints[lastFailure.Fingerprint]++
				if failureFingerprints[lastFailure.Fingerprint] >= s.currentRetryPolicy().maxSameFingerprint {
					break
				}
			}
			continue
		}
		if response.StatusCode >= 200 && response.StatusCode < 300 {
			// xAI sometimes returns capacity/high-demand errors under HTTP 200 as the
			// first JSON/SSE payload. Probe before client hand-off so we can rotate.
			if earlyFailure := probeSuccessResponseForRetry(response); earlyFailure != nil {
				earlyFailure.AccountID = credential.ID
				earlyFailure.AccountName = credential.Name
				failureAttempts.captureEarlyBodyFailure(credential, responseStartedAt, response, earlyFailure)
				lastFailure = earlyFailure
				lastErr = earlyFailure
				if earlyFailure.RequestScoped {
					lease.Release()
					s.logger.Warn("upstream_request_scoped_failure", "request_id", input.RequestID, "account_id", credential.ID, "provider", credential.Provider, "status", response.StatusCode, "upstream_code", earlyFailure.UpstreamCode, "stage", "early_body_probe")
					break attemptLoop
				}
				lease.Release()
				if earlyFailure.PlatformBusy {
					s.logger.Warn("upstream_capacity_busy", "request_id", input.RequestID, "account_id", credential.ID, "provider", credential.Provider, "status", response.StatusCode, "upstream_code", earlyFailure.UpstreamCode, "stage", "early_body_probe")
					failureFingerprints[earlyFailure.Fingerprint]++
					if failureFingerprints[earlyFailure.Fingerprint] >= s.currentRetryPolicy().maxSameFingerprint {
						break attemptLoop
					}
					continue
				}
				s.logger.Warn("upstream_early_body_failure", "request_id", input.RequestID, "account_id", credential.ID, "provider", credential.Provider, "code", earlyFailure.Code)
				failureFingerprints[earlyFailure.Fingerprint]++
				if failureFingerprints[earlyFailure.Fingerprint] >= s.currentRetryPolicy().maxSameFingerprint {
					break attemptLoop
				}
				continue
			}
			s.selector.markSuccess(ctx, credential, lease.QuotaProbe)
			// Keep prompt-cache affinity on the account that actually served this turn.
			// Permanent quota/auth failover rebinds so the next turn rebuilds cache on the new account;
			// temporary capacity borrow only refreshes TTL and preserves the original binding.
			if affinityKey != "" {
				if permanentStickyBreak {
					if err := s.selector.RebindSticky(ctx, affinityKey, credential.ID); err != nil {
						s.logger.Warn("sticky_rebind_failed", "request_id", input.RequestID, "account_id", credential.ID, "error", err)
					} else {
						s.logger.Debug("sticky_rebind_after_failover", "request_id", input.RequestID, "account_id", credential.ID)
					}
				} else if err := s.selector.RefreshSticky(ctx, affinityKey, credential.ID); err != nil {
					s.logger.Warn("sticky_refresh_failed", "request_id", input.RequestID, "account_id", credential.ID, "error", err)
				}
			}
			if diagnostic := response.RecoveredPrimaryFailure; diagnostic != nil {
				recoveredFailure := newHTTPUpstreamFailure(diagnostic.StatusCode, diagnostic.Body, credential.ID, credential.Name)
				if recoveredFailure.AccountBlocked || (credential.Provider == accountdomain.ProviderBuild && s.shouldInvalidateBuildForbidden(recoveredFailure)) {
					reason := fmt.Sprintf("%s primary endpoint denied account access", credential.Provider)
					if !s.markReauthRequired(ctx, input.RequestID, credential, reason) {
						s.selector.MarkModelAccessDenied(ctx, credential, route.UpstreamModel, 0)
					}
				}
			}
		}
		accountID := credential.ID
		var once sync.Once
		finalize := func(usage Usage, responseID, errorCode string) {
			once.Do(func() {
				successful := response.StatusCode >= 200 && response.StatusCode < 300 && errorCode == ""
				lease.completeSelectorObservation(successful)
				lease.Release()
				budget := newFinalizationBudget(string(operation), string(route.Provider))
				if isUpstreamStreamFailure(errorCode) {
					_ = budget.run("account_health", finalizationHealthBudget, func(stageCtx context.Context) error {
						s.selector.MarkFailure(stageCtx, credential, http.StatusBadGateway, 0)
						return nil
					})
				}
				now := time.Now().UTC()
				record := auditBase
				record.AccountID = &accountID
				record.AccountName = credential.Name
				record.StatusCode = response.StatusCode
				record.InputTokens = usage.InputTokens
				record.CachedInputTokens = usage.CachedInputTokens
				record.OutputTokens = usage.OutputTokens
				record.ReasoningTokens = usage.ReasoningTokens
				record.TotalTokens = usage.TotalTokens
				record.CostInUSDTicks = usage.CostInUSDTicks
				imagePricing, imagePriced := audit.EstimateOfficialImageCost(pricingModel, "", response.QuotaUnits)
				if imagePriced {
					record.MediaOutputImages = int64(max(0, response.QuotaUnits))
				}
				tokenPricing, tokenPriced := audit.EstimateOfficialCost(pricingModel, usage.InputTokens, usage.CachedInputTokens, usage.OutputTokens, usage.ContextInputTokens)
				if response.StatusCode >= 200 && response.StatusCode < 300 && errorCode == "" && imagePriced {
					record.EstimatedCostInUSDTicks = imagePricing.CostInUSDTicks
					record.PricingModel = imagePricing.Model
					record.PricingVersion = audit.OfficialPricingAsOf
				} else if tokenPriced {
					record.EstimatedCostInUSDTicks = tokenPricing.CostInUSDTicks
					record.PricingModel = tokenPricing.Model
					record.PricingVersion = audit.OfficialPricingAsOf
				}
				record.NumSourcesUsed = usage.NumSourcesUsed
				record.NumServerSideToolsUsed = usage.NumServerSideToolsUsed
				record.ContextInputTokens = usage.ContextInputTokens
				record.ContextOutputTokens = usage.ContextOutputTokens
				record.DurationMS = time.Since(startedAt).Milliseconds()
				record.ErrorCode = errorCode
				attempts := failureAttempts.snapshot()
				if response.StatusCode < 200 || response.StatusCode >= 300 || errorCode != "" || len(attempts) > 0 {
					record.Attempts = attempts
				}
				record.AttemptCount = len(attempts)
				record.CreatedAt = now
				applyGenerationTiming(&record, timing)
				applyAuditEgress(&record, egressTrace, route.Provider)
				if supportsStoredResponses && operation == audit.OperationResponses && responseID != "" && successful {
					err := budget.run("response_ownership", finalizationOwnershipBudget, func(stageCtx context.Context) error {
						return s.responses.Save(stageCtx, inferencedomain.ResponseOwnership{ResponseID: responseID, AccountID: accountID, ClientKeyID: input.ClientKey.ID, Provider: route.Provider, PromptCacheKey: ownershipPromptCacheKey, ReasoningReplayKey: reasoningReplayKey, ExpiresAt: now.Add(responseOwnershipTTL), CreatedAt: now, UpdatedAt: now})
					})
					if err != nil {
						s.logger.Error("response_ownership_save_failed", "response_id", responseID, "client_key_id", input.ClientKey.ID, "account_id", accountID, "provider", route.Provider, "error", err)
					}
				}
				if successful && lease.QuotaMode != "" {
					if lease.QuotaMode != "weekly" {
						// Console local windows are open/closed flags driven by upstream
						// 429 exhaustion + timed recovery. Do not burn remaining on success.
						if quotaKind, _ := s.providers.QuotaKind(credential.Provider); quotaKind != provider.QuotaLocalWindow {
							units := max(1, response.QuotaUnits)
							var updated bool
							err := budget.run("quota_decrement", finalizationQuotaBudget, func(stageCtx context.Context) error {
								var decrementErr error
								updated, decrementErr = s.accounts.DecrementQuota(stageCtx, accountID, lease.QuotaMode, units)
								return decrementErr
							})
							if err != nil {
								s.logger.Warn("provider_quota_decrement_failed", "provider", credential.Provider, "account_id", accountID, "mode", lease.QuotaMode, "units", units, "error", err)
							} else if updated {
								s.selector.ConsumeQuota(credential.Provider, accountID, lease.QuotaMode, units)
							}
						}
					}
				}
				if err := budget.run("audit", finalizationAuditBudget, func(stageCtx context.Context) error {
					return s.audits.Create(stageCtx, record)
				}); err != nil {
					s.logger.Error("request_usage_write_failed", "event_id", record.EventID, "request_id", input.RequestID, "error", err)
				}
				if usage.ResponseModel != "" {
					_ = budget.run("observed_model", finalizationMetadataBudget, func(stageCtx context.Context) error {
						return s.accounts.ObserveResponseModel(stageCtx, accountID, usage.ResponseModel)
					})
				}
				if successful && lease.QuotaMode != "" {
					if quotaKind, _ := s.providers.QuotaKind(credential.Provider); quotaKind == provider.QuotaRemoteWindow {
						s.accounts.QueueQuotaRefresh(accountID, lease.QuotaMode)
					}
				}
				outcome := "failed"
				if successful {
					outcome = "success"
				}
				timing.finish(s.logger, outcome)
			})
		}
		response.Body = &firstByteReadCloser{ReadCloser: response.Body, mark: timing.markFirstBody}
		recordStreamFailure := func(diagnostic StreamFailureDiagnostic) {
			failureAttempts.captureStreamFailure(credential, responseStartedAt, response, diagnostic)
		}
		timingHandedOff = true
		return &Result{StatusCode: response.StatusCode, Status: response.Status, Header: response.Header, Body: &finalizingBody{ReadCloser: response.Body, finalize: func() { finalize(Usage{}, "", "stream_closed") }}, RecordStreamFailure: recordStreamFailure, Finalize: finalize}, nil
	}
	if lastFailure != nil {
		record := auditBase
		record.StatusCode = lastFailure.HTTPStatus
		record.DurationMS = time.Since(startedAt).Milliseconds()
		record.ErrorCode = lastFailure.AuditCode()
		record.Attempts = failureAttempts.snapshot()
		record.AttemptCount = len(record.Attempts)
		record.CreatedAt = time.Now().UTC()
		applyGenerationTiming(&record, timing)
		applyAuditEgress(&record, egressTrace, route.Provider)
		if lastFailure.AccountID != 0 {
			accountID := lastFailure.AccountID
			record.AccountID = &accountID
			record.AccountName = lastFailure.AccountName
		}
		persistCtx, cancel := context.WithTimeout(context.Background(), finalizationTimeout)
		defer cancel()
		if err := s.audits.Create(persistCtx, record); err != nil {
			s.logger.Error("request_usage_write_failed", "event_id", record.EventID, "request_id", input.RequestID, "error", err)
		}
		timing.finish(s.logger, "failed")
		return nil, lastFailure
	}
	if lastErr == nil {
		lastErr = ErrNoAvailableAccount
	}
	record := auditBase
	record.StatusCode = http.StatusServiceUnavailable
	record.DurationMS = time.Since(startedAt).Milliseconds()
	record.ErrorCode = "upstream_unavailable"
	record.Attempts = failureAttempts.snapshot()
	record.AttemptCount = len(record.Attempts)
	record.CreatedAt = time.Now().UTC()
	applyGenerationTiming(&record, timing)
	applyAuditEgress(&record, egressTrace, route.Provider)
	persistCtx, cancel := context.WithTimeout(context.Background(), finalizationTimeout)
	defer cancel()
	if err := s.audits.Create(persistCtx, record); err != nil {
		s.logger.Error("request_usage_write_failed", "event_id", record.EventID, "request_id", input.RequestID, "error", err)
	}
	timing.finish(s.logger, "failed")
	return nil, fmt.Errorf("%w: %w", ErrNoAvailableAccount, lastErr)
}

func isUpstreamStreamFailure(errorCode string) bool {
	switch errorCode {
	case "upstream_stream_incomplete", "upstream_stream_interrupted":
		return true
	default:
		return false
	}
}

func isRetryableTransportFailure(providerValue accountdomain.Provider, err error) bool {
	return providerValue != accountdomain.ProviderBuild || !neterrorpkg.IsResponseHeaderTimeout(err)
}

func isSSOCredentialRejected(err error, credential accountdomain.Credential) bool {
	if credential.AuthType != accountdomain.AuthTypeSSO || err == nil {
		return false
	}
	if errors.Is(err, provider.ErrUnauthorized) {
		return true
	}
	status, ok := provider.ErrorHTTPStatus(err)
	return ok && status == http.StatusUnauthorized
}

func (s *Service) markSSOCredentialRejected(ctx context.Context, credential accountdomain.Credential, reason string) {
	if credential.AuthType != accountdomain.AuthTypeSSO {
		return
	}
	writeCtx, cancel := context.WithTimeout(context.WithoutCancel(ctx), finalizationTimeout)
	defer cancel()
	if err := s.accounts.MarkReauthRequired(writeCtx, credential.ID, reason); err != nil {
		s.logger.Error("account_reauth_required_write_failed", "account_id", credential.ID, "provider", credential.Provider, "error", err)
	}
	// Discard the process-local one-second candidate snapshot even if persistence fails,
	// preventing the invalid account from being selected by the next request.
	s.selector.MarkQuotaStateChanged(credential.Provider)
}

func (s *Service) queueAccountModelSync(accountID uint64) {
	syncer, ok := s.models.(accountModelSyncer)
	if !ok || accountID == 0 {
		return
	}
	s.modelSyncMu.Lock()
	if s.modelSyncing == nil {
		s.modelSyncing = make(map[uint64]struct{})
	}
	if _, exists := s.modelSyncing[accountID]; exists {
		s.modelSyncMu.Unlock()
		return
	}
	s.modelSyncing[accountID] = struct{}{}
	s.modelSyncMu.Unlock()

	go func() {
		defer func() {
			s.modelSyncMu.Lock()
			delete(s.modelSyncing, accountID)
			s.modelSyncMu.Unlock()
		}()
		ctx, cancel := context.WithTimeout(context.Background(), modelCatalogRefreshTimeout)
		defer cancel()
		logger := s.logger
		if logger == nil {
			logger = slog.Default()
		}
		count, err := syncer.SyncAccount(ctx, accountID)
		if err != nil {
			logger.Warn("model_etag_refresh_failed", "account_id", accountID, "error", err)
			return
		}
		logger.Info("model_etag_refresh_completed", "account_id", accountID, "models", count)
	}()
}

func rewriteAliasedModel(body []byte, publicModel, reasoningEffort string, operation audit.Operation) ([]byte, error) {
	var payload map[string]any
	if err := json.Unmarshal(body, &payload); err != nil {
		return nil, fmt.Errorf("解析兼容模型请求: %w", err)
	}
	payload["model"] = publicModel
	if reasoningEffort != "" {
		switch operation {
		case audit.OperationChat:
			payload["reasoning_effort"] = reasoningEffort
		case audit.OperationMessages:
			config, _ := payload["output_config"].(map[string]any)
			if config == nil {
				config = make(map[string]any)
			}
			config["effort"] = reasoningEffort
			payload["output_config"] = config
		default:
			reasoning, _ := payload["reasoning"].(map[string]any)
			if reasoning == nil {
				reasoning = make(map[string]any)
			}
			reasoning["effort"] = reasoningEffort
			payload["reasoning"] = reasoning
		}
	}
	return json.Marshal(payload)
}

type ResourceInput struct {
	ClientKey  clientkey.Key
	ResponseID string
	RawQuery   string
}

func (s *Service) cancelBillingReservation(eventID string) {
	ctx, cancel := context.WithTimeout(context.Background(), finalizationTimeout)
	defer cancel()
	if err := s.clientKeys.CancelBilling(ctx, eventID); err != nil {
		s.logger.Error("billing_reservation_cancel_failed", "event_id", eventID, "error", err)
	}
}

func newAuditEventID() string {
	value, err := security.NewOpaqueToken(18)
	if err != nil || value == "" {
		return fmt.Sprintf("evt_%d", time.Now().UnixNano())
	}
	return "evt_" + value
}

func (s *Service) GetResponse(ctx context.Context, input ResourceInput) (*Result, error) {
	return s.forwardOwnedResponse(ctx, input, http.MethodGet)
}

func (s *Service) DeleteResponse(ctx context.Context, input ResourceInput) (*Result, error) {
	return s.forwardOwnedResponse(ctx, input, http.MethodDelete)
}

func (s *Service) forwardOwnedResponse(ctx context.Context, input ResourceInput, method string) (*Result, error) {
	ownership, err := s.responses.Get(ctx, input.ResponseID, input.ClientKey.ID, time.Now().UTC())
	if err != nil {
		return nil, ErrResponseNotFound
	}
	if !s.providers.SupportsStoredResponses(ownership.Provider) {
		_ = s.responses.Delete(ctx, input.ResponseID, input.ClientKey.ID)
		return nil, ErrResponseNotFound
	}
	adapter, ok := s.providers.Responses(ownership.Provider)
	if !ok {
		return nil, ErrResponseAccountUnavailable
	}
	operation := "response_get"
	if method == http.MethodDelete {
		operation = "response_delete"
	}
	physicalCallCtx := infraegress.WithPhysicalCallTrace(ctx, string(ownership.Provider), operation)
	lease, err := s.selector.AcquirePinned(ctx, ownership.Provider, ownership.AccountID, "", "", false)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrResponseAccountUnavailable, err)
	}
	credential, err := s.accounts.EnsureCredential(ctx, lease.Credential, false)
	if err != nil {
		lease.Release()
		return nil, fmt.Errorf("%w: %w", ErrResponseAccountUnavailable, err)
	}
	path := "/responses/" + url.PathEscape(input.ResponseID)
	if input.RawQuery != "" {
		path += "?" + input.RawQuery
	}
	response, err := adapter.ForwardResponse(physicalCallCtx, provider.ResponseResourceRequest{Credential: credential, Method: method, Path: path})
	if err != nil {
		if isSSOCredentialRejected(err, credential) {
			s.markSSOCredentialRejected(ctx, credential, fmt.Sprintf("%s SSO credential rejected", credential.Provider))
		}
		lease.Release()
		return nil, err
	}
	if response.StatusCode == http.StatusUnauthorized {
		response.Body.Close()
		if credential.AuthType == accountdomain.AuthTypeSSO {
			s.markSSOCredentialRejected(ctx, credential, fmt.Sprintf("%s SSO credential rejected", credential.Provider))
			lease.Release()
			return nil, ErrResponseAccountUnavailable
		}
		if s.markPermanentlyUnrefreshableCredentialRejected(ctx, credential) {
			lease.Release()
			return nil, fmt.Errorf("%w: %w", ErrResponseAccountUnavailable, accountapp.ErrCredentialRefreshPermanent)
		}
		refreshed, refreshErr := s.accounts.EnsureCredential(ctx, credential, true)
		if refreshErr != nil {
			if errors.Is(refreshErr, accountapp.ErrCredentialRefreshPermanent) {
				s.markCredentialRejectedAfterPermanentRefresh(ctx, credential)
			}
			lease.Release()
			return nil, refreshErr
		}
		response, err = adapter.ForwardResponse(physicalCallCtx, provider.ResponseResourceRequest{Credential: refreshed, Method: method, Path: path})
		credential = refreshed
		if err != nil {
			lease.Release()
			return nil, err
		}
	}
	if response.StatusCode >= 200 && response.StatusCode < 300 {
		s.selector.markSuccess(ctx, credential, false)
		if method == http.MethodDelete {
			_ = s.responses.Delete(ctx, input.ResponseID, input.ClientKey.ID)
		}
	} else if response.StatusCode == http.StatusNotFound || response.StatusCode == http.StatusGone {
		_ = s.responses.Delete(ctx, input.ResponseID, input.ClientKey.ID)
	}
	var once sync.Once
	release := func() { once.Do(lease.Release) }
	finalize := func(Usage, string, string) { release() }
	return &Result{StatusCode: response.StatusCode, Status: response.Status, Header: response.Header, Body: &finalizingBody{ReadCloser: response.Body, finalize: release}, Finalize: finalize}, nil
}

// markPermanentlyUnrefreshableCredentialRejected removes an account from the pool after a real upstream request confirms its access token is invalid.
func (s *Service) markPermanentlyUnrefreshableCredentialRejected(ctx context.Context, credential accountdomain.Credential) bool {
	if !credential.RefreshPermanent {
		return false
	}
	s.markCredentialRejectedAfterPermanentRefresh(ctx, credential)
	return true
}

func (s *Service) markCredentialRejectedAfterPermanentRefresh(ctx context.Context, credential accountdomain.Credential) {
	_ = s.accounts.MarkReauthRequired(ctx, credential.ID, fmt.Sprintf("%s OAuth access token rejected after permanent refresh failure", credential.Provider))
	s.selector.MarkQuotaStateChanged(credential.Provider)
}

// tryRotateResinEgress releases the Resin sticky lease so the next CONNECT can
// land on a different exit IP. Caller tracks per-account rotation count against maxRotations.
func (s *Service) tryRotateResinEgress(ctx context.Context, requestID string, credential accountdomain.Credential, lease *accountLease, egressRotateCount map[uint64]int, maxRotations int) bool {
	if s == nil || s.resinAdmin == nil || !s.resinAdmin.Enabled() {
		return false
	}
	if credential.ID == 0 || maxRotations <= 0 {
		return false
	}
	if egressRotateCount[credential.ID] >= maxRotations {
		return false
	}
	identity := infraegress.StickyAccountIdentity(credential)
	if identity == "" {
		return false
	}
	oldIP, oldNode, err := s.resinAdmin.RotateAccountLease(ctx, identity)
	if err != nil {
		s.logger.Warn("resin_lease_release_failed",
			"request_id", requestID,
			"account_id", credential.ID,
			"sticky_account", identity,
			"error", err,
		)
		return false
	}
	egressRotateCount[credential.ID]++
	if s.proxyClients != nil {
		s.proxyClients.DropBuildProxyClients()
	}
	_ = lease
	s.logger.Warn("resin_egress_rotated",
		"request_id", requestID,
		"account_id", credential.ID,
		"account_name", credential.Name,
		"sticky_account", identity,
		"old_egress_ip", oldIP,
		"old_node_hash", oldNode,
		"rotation", egressRotateCount[credential.ID],
		"max_rotations", maxRotations,
		"reason", "spending_limit_402",
	)
	return true
}

func readRetryableBody(body io.ReadCloser) ([]byte, error) {
	if body == nil {
		return nil, nil
	}
	defer body.Close()
	data, _, err := provider.ReadDiagnosticBody(body)
	return data, err
}

func parseFreeQuotaExhaustion(body []byte) (int64, int64, bool) {
	text := strings.ToLower(string(body))
	if !strings.Contains(text, "subscription:free-usage-exhausted") {
		return 0, 0, false
	}
	matches := freeQuotaUsagePattern.FindSubmatch(body)
	if len(matches) != 3 {
		return 0, 0, true
	}
	used, usedErr := strconv.ParseInt(string(matches[1]), 10, 64)
	limit, limitErr := strconv.ParseInt(string(matches[2]), 10, 64)
	if usedErr != nil || limitErr != nil {
		return 0, 0, true
	}
	return used, limit, true
}

type finalizingBody struct {
	io.ReadCloser
	finalize func()
}

func (b *finalizingBody) Close() error {
	err := b.ReadCloser.Close()
	if b.finalize != nil {
		b.finalize()
	}
	return err
}

func isRetryable(status int) bool {
	return status == 402 || status == 403 || status == 429 || status >= 500
}

func isRetryableResponse(response *provider.Response, upstreamProvider accountdomain.Provider) bool {
	if response == nil || !isRetryable(response.StatusCode) {
		return false
	}
	if forcesAccountFailover(response.StatusCode, upstreamProvider) {
		return true
	}
	return !strings.EqualFold(strings.TrimSpace(response.Header.Get("X-Should-Retry")), "false")
}

func (s *Service) isRetryableResponse(response *provider.Response, upstreamProvider accountdomain.Provider) bool {
	if response == nil || !s.statusAllowsRetry(response.StatusCode) {
		return false
	}
	// Build 402/403 account billing/permission still force rotation even if 403 removed from list?
	// Keep forcesAccountFailover only when status is still allowed OR is 402/403 for Build.
	if forcesAccountFailover(response.StatusCode, upstreamProvider) {
		return true
	}
	return !strings.EqualFold(strings.TrimSpace(response.Header.Get("X-Should-Retry")), "false")
}

// forcesAccountFailover keeps Build account-scoped billing and permission failures on the
// account-rotation path so their state can be recorded before another account is selected.
func forcesAccountFailover(status int, upstreamProvider accountdomain.Provider) bool {
	return upstreamProvider == accountdomain.ProviderBuild && (status == http.StatusPaymentRequired || status == http.StatusForbidden)
}

func parseRetryAfter(value string, now time.Time) time.Duration {
	value = strings.TrimSpace(value)
	if seconds, err := strconv.Atoi(value); err == nil && seconds > 0 {
		return time.Duration(seconds) * time.Second
	}
	if parsed, err := http.ParseTime(value); err == nil && parsed.After(now) {
		return parsed.Sub(now)
	}
	return 0
}

func firstError(values ...error) error {
	for _, value := range values {
		if value != nil {
			return value
		}
	}
	return errors.New("未知上游错误")
}

func truncateForLog(value string, max int) string {
	value = strings.TrimSpace(value)
	if max <= 0 || len(value) <= max {
		return value
	}
	return value[:max]
}
